services:
  - type: web
    name: sickle-cell-ai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"

  - type: static_site
    name: sickle-cell-ai-frontend
    runtime: node
    buildCommand: cd SICKLE-CELL-UI/sickle-cell-ui && npm install && npm run build
    staticPublishPath: SICKLE-CELL-UI/sickle-cell-ui/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://sickle-cell-ai-backend.onrender.com
